import type { Metadata } from 'next'

import { Inter } from 'next/font/google'

import { Footer } from '@/components/layout/footer'
import { Toaster } from '@/components/ui/sonner'

import { cn } from '@/lib/utils'

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' })

import '@/style/globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang='pt-br' className={cn('dark', 'font-sans', inter.variable)}>
      <body className={`${inter.className}`}>
        <div className='flex h-full flex-col'>
          <div className='flex-1'>{children}</div>
          <Footer />
        </div>

        <Toaster />
      </body>
    </html>
  )
}
